services:
  tlscheckin:
    image: ${TLSCHECKIN_IMAGE:-tlscheckin:local}
    build: .
    container_name: tlscheckin-${BRANCH_NAME:-main}
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    env_file:
      - .env

    volumes:
      - ./persistent-data-${BRANCH_NAME:-main}:/app/data

    networks:
      - proxy

networks:
  proxy:
    external: true
